# Generated by Django 4.1 on 2023-05-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0010_data_collected_geolocation_totaltime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_collected',
            name='canvas',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data_collected',
            name='canvas_totaltime',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data_collected',
            name='plugins',
            field=models.CharField(blank=True, default='Something', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data_collected',
            name='plugins_totaltime',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data_collected',
            name='screen_res_height',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_collected',
            name='screen_res_width',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_collected',
            name='webgl',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data_collected',
            name='webgl_totaltime',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
